"""Add is_origin and is_destination to airports

Revision ID: a085810eaf1d
Revises: 002
Create Date: 2025-11-20 22:59:37.738556+00:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a085810eaf1d"
down_revision: Union[str, None] = "002"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "airports",
        sa.Column(
            "is_origin",
            sa.Boolean(),
            server_default="false",
            nullable=False,
            comment="Whether this airport can be used as an origin",
        ),
    )
    op.add_column(
        "airports",
        sa.Column(
            "is_destination",
            sa.Boolean(),
            server_default="false",
            nullable=False,
            comment="Whether this airport can be used as a destination",
        ),
    )
    op.add_column(
        "api_costs",
        sa.Column(
            "extra_metadata", sa.Text(), nullable=True, comment="Additional metadata as JSON string"
        ),
    )
    op.alter_column(
        "api_costs",
        "input_tokens",
        existing_type=sa.INTEGER(),
        server_default=None,
        existing_comment="Number of input tokens consumed",
        existing_nullable=False,
    )
    op.alter_column(
        "api_costs",
        "output_tokens",
        existing_type=sa.INTEGER(),
        server_default=None,
        existing_comment="Number of output tokens generated",
        existing_nullable=False,
    )
    op.alter_column(
        "api_costs",
        "cache_hit",
        existing_type=sa.BOOLEAN(),
        server_default=None,
        existing_comment="Whether this was a cache hit (no actual API call)",
        existing_nullable=False,
    )
    op.drop_column("api_costs", "metadata")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "api_costs",
        sa.Column(
            "metadata",
            sa.TEXT(),
            autoincrement=False,
            nullable=True,
            comment="Additional metadata as JSON string",
        ),
    )
    op.alter_column(
        "api_costs",
        "cache_hit",
        existing_type=sa.BOOLEAN(),
        server_default=sa.text("false"),
        existing_comment="Whether this was a cache hit (no actual API call)",
        existing_nullable=False,
    )
    op.alter_column(
        "api_costs",
        "output_tokens",
        existing_type=sa.INTEGER(),
        server_default=sa.text("0"),
        existing_comment="Number of output tokens generated",
        existing_nullable=False,
    )
    op.alter_column(
        "api_costs",
        "input_tokens",
        existing_type=sa.INTEGER(),
        server_default=sa.text("0"),
        existing_comment="Number of input tokens consumed",
        existing_nullable=False,
    )
    op.drop_column("api_costs", "extra_metadata")
    op.drop_column("airports", "is_destination")
    op.drop_column("airports", "is_origin")
    # ### end Alembic commands ###
